// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Health Checking for API services",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Health Checking",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.HealthzResult"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.HealthzResult": {
            "type": "object",
            "properties": {
                "details": {
                    "$ref": "#/definitions/dto.HealthzResultDetails"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ok",
                        "error"
                    ],
                    "example": "ok"
                }
            }
        },
        "dto.HealthzResultDetail": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "enum": [
                        "ok",
                        "error"
                    ],
                    "example": "ok"
                }
            }
        },
        "dto.HealthzResultDetails": {
            "type": "object",
            "properties": {
                "db": {
                    "$ref": "#/definitions/dto.HealthzResultDetail"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "ToGo List API",
	Description:      "This is an API for ToGo List application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
