basePath: /v1
definitions:
  dto.CreateListInput:
    properties:
      description:
        type: string
      priority:
        type: integer
      title:
        type: string
    required:
    - description
    - title
    type: object
  dto.HealthzResult:
    properties:
      details:
        $ref: '#/definitions/dto.HealthzResultDetails'
      status:
        enum:
        - ok
        - error
        example: ok
        type: string
    type: object
  dto.HealthzResultDetail:
    properties:
      status:
        enum:
        - ok
        - error
        example: ok
        type: string
    type: object
  dto.HealthzResultDetails:
    properties:
      db:
        $ref: '#/definitions/dto.HealthzResultDetail'
    type: object
  dto.List:
    properties:
      description:
        type: string
      id:
        type: integer
      priority:
        type: integer
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is an API for ToGo List application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ToGo List API
  version: "1.0"
paths:
  /healthz:
    get:
      description: Health Checking for API services
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HealthzResult'
      summary: Health Checking
  /lists:
    post:
      consumes:
      - application/json
      description: Create a single List
      parameters:
      - description: Create List
        in: body
        name: list
        required: true
        schema:
          $ref: '#/definitions/dto.CreateListInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.List'
      summary: Create List
swagger: "2.0"
